name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run date command
      id: date
      run: |
        buildTime=$(date +%Y-%m-%d" "%X)
        echo "BUILD_TIME=$buildTime" >> $GITHUB_OUTPUT

    - name: Set GH_TAG
      id: tag
      run: |
        echo "GH_BUILD_TAG=dnsmasq" >> $GITHUB_OUTPUT
        echo "GH_LATEST_TAG=latest" >> $GITHUB_OUTPUT

    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        dockerfile: Dockerfile-dnsmasq # Use Dockerfile-dnsmasq instead of the default Dockerfile 
        push: true
        # platforms: linux/amd64
        # platforms: linux/amd64,linux/arm64
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:${{ steps.tag.outputs.GH_BUILD_TAG }}
        build-args: |
          BUILD_TIME=${{ steps.date.outputs.BUILD_TIME }}
        # ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:${{ steps.tag.outputs.GH_LATEST_TAG }}

