name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      base_image:
        description: 'Base image to use for the Docker build'
        required: true
        type: choice
        options:
          - alpine
          - caddy
          - caddy-s6
      caddy_version:
        description: 'Version of Caddy to build from (will always be alpine)'
        required: true
        default: '2.8.1'
      s6_version:
        description: 'Version of S6-Overlay to include in the build'
        required: true
        default: '3.2.0.0'
            
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run date command
      id: date
      run: |
        buildTime=$(date +%Y-%m-%d" "%X)
        echo "BUILD_TIME=$buildTime" >> $GITHUB_OUTPUT
        # echo "::set-output name=output::$DATE"

    - name: Set BASE_IMAGE and GH_TAG
      id: tag
      run: |
        echo "IS_S6=false" >> $GITHUB_OUTPUT
        if [ "${{ github.event.inputs.base_image }}" == "alpine" ]; then
          echo "BASE_IMAGE=alpine:latest" >> $GITHUB_OUTPUT
          buildTag=$(date +%Y-%m-%d-%H-%M)
          echo "GH_TAG=$buildTag" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.inputs.base_image }}" == "caddy" ]; then
            echo "BASE_IMAGE=caddy:${{ github.event.inputs.caddy_version }}-alpine" >> $GITHUB_OUTPUT
            echo "GH_TAG=caddy-${{ github.event.inputs.caddy_version }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.inputs.base_image }}" == "caddy-s6" ]; then
          echo "IS_S6=true" >> $GITHUB_OUTPUT
          echo "BASE_IMAGE=caddy:${{ github.event.inputs.caddy_version }}-alpine" >> $GITHUB_OUTPUT
          echo "GH_TAG=caddy-${{ github.event.inputs.caddy_version }}-s6" >> $GITHUB_OUTPUT
        else
          echo "Invalid base image specified" >&2
          exit 1
        fi
  
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64
        # platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:${{ steps.tag.outputs.GH_TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:latest
        build-args: |
          BASE_IMAGE=${{ steps.tag.outputs.BASE_IMAGE }}
          IS_S6=${{ steps.tag.outputs.IS_S6 }}
          S6_OVERLAY_VERSION=${{ github.event.inputs.s6_version }}
          BUILD_TIME=${{ steps.date.outputs.BUILD_TIME }}
          BASE_IMAGE_TMP=${{ steps.tag.outputs.BASE_IMAGE }} # put her to get around an issue with LABEL in the Dockerfile
