name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      base_image:
        description: 'Base image to use for the Docker build'
        required: true
        type: choice
        options:
          - alpine
          - caddy
          - caddy-s6
      caddy_version:
        description: 'Version of Caddy to build from (will always be alpine)'
        required: true
        default: '2.8.2'
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run date command
      id: date
      run: |
        buildTime=$(date +%Y-%m-%d" "%X)
        echo "BUILD_TIME=$buildTime" >> $GITHUB_OUTPUT
        # echo "::set-output name=output::$DATE"

    - name: Set BASE_IMAGE and GH_TAG
      id: tag
      run: |
        if [ "${{ github.event.inputs.base_image }}" == "alpine" ]; then
          echo "BASE_IMAGE=alpine:latest" >> $GITHUB_ENV
          buildTag=$(date +%Y-%m-%d-%H-%M)
          echo "GH_TAG=$buildTag" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.inputs.base_image }}" == "caddy" ]; then
            echo "BASE_IMAGE=caddy:${{ github.event.inputs.caddy_version }}-alpine" >> $GITHUB_ENV
            echo "GH_TAG=caddy-${{ github.event.inputs.caddy_version }}" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.base_image }}" == "caddy-s6" ]; then
          echo "BASE_IMAGE=caddy:${{ github.event.inputs.caddy_version }}-alpine" >> $GITHUB_ENV
          echo "GH_TAG=caddy-${{ github.event.inputs.caddy_version }}-s6" >> $GITHUB_ENV
        else
          echo "Invalid base image specified" >&2
          exit 1
        fi
  
    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:${{ steps.tag.outputs.GH_TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq:latest
        build-args: |
          BUILD_TIME=${{ steps.date.outputs.BUILD_TIME }}
